-- vim.cmd [[highlight IndentBlanklineIndent1 guibg=#1F1F1F gui=nocombine]]
-- vim.cmd [[highlight IndentBlanklineIndent2 guibg=#2B2B2B gui=nocombine]]
-- vim.cmd [[highlight IndentBlanklineContextChar guifg=#FFFFFF gui=nocombine]]
--
-- require("indent_blankline").setup {
--     show_current_context = true,
--     show_current_context_start = true,
--     show_trailing_blankline_indent = false,
--     char_highlight_list = {
--         "IndentBlanklineIndent1",
--         "IndentBlanklineIndent2",
--     },
--     space_char_highlight_list = {
--         "IndentBlanklineIndent1",
--         "IndentBlanklineIndent2",
--     },
-- }
